experiment:
  name: lego_feature_teacher_full_psnr20_quickwin
  seed: 2025
  output_dir: results/lego/feat_t_full/runs/teacher_full_psnr20_quickwin
  progress_desc: PSNR20_quickwin

data:
  dataset_root: ../3dgs/data/nerf_synthetic/lego
  teacher_outputs: teacher/outputs/lego/test_white/ours_30000
  teacher_depth_dir: teacher/outputs/lego/test_white/ours_30000/depth
  camera_json: teacher/outputs/lego/test_white/ours_30000/transforms_test_white.json
  background_color: [1.0, 1.0, 1.0]
  batch_size: 16384
  ray_chunk: 2048
  near: 2.0
  far: 6.0
  samples_per_ray: 128
  bbox_min: [-1.5, -1.5, -1.5]
  bbox_max: [1.5, 1.5, 1.5]
  perturb: true

teacher:
  type: gaussian_splatting
  checkpoint: teacher/checkpoints/lego/point_cloud/iteration_30000/point_cloud.ply
  render_stats: teacher/outputs/lego/test_white/ours_30000/render_stats.json

student:
  type: kilo_uniform_mlp
  grid_resolution: [8, 8, 8]
  hidden_dim: 192
  num_layers: 5
  activation: relu
  density_bias: -1.0
  color_bias: 0.0
  regularization_weight: 5.0e-5
  enable_boundary_blend: true
  boundary_blend_margin: 0.08

train:
  max_steps: 30000
  phases:
    - name: projector_warmup
      end_step: 2000
      optimize: [projector]
      freeze_student: true
      phase_feature_scale: 0.7
      force_feature_on: true
    - name: joint_training
      end_step: 30000
      optimize: [student, projector]
      freeze_student: false
      phase_feature_scale: 1.0
  eval_interval: 5000
  checkpoint_interval: 5000
  lr: 3.0e-4
  lr_schedule: cosine
  lr_schedule_steps: 30000
  lr_schedule_min_lr: 3.0e-5
  gradient_clip_norm: 1.0
  ema_decay: 0.999

loss:
  color:
    type: l2
    weight: 1.5
  opacity:
    type: l1
    weight: 0.15
    target: 0.03
    target_weight: 0.2
    warmup_steps: 2000
    schedule: cosine
    schedule_duration: 6000
    background_threshold: 0.05
  depth:
    type: smooth_l1
    weight: 0.2
    alpha_threshold: 0.6
  feature_l2:
    weight: 0.08
    warmup:
      steps: 4000
      type: linear
      start_weight: 0.0
  feature_cos:
    weight: 0.02
    warmup:
      steps: 4000
      type: linear
      start_weight: 0.0

feature_targets:
  l2_target: 0.04
  cos_target: 0.01

feature_pipeline:
  enabled: true
  teacher_mode: gaussian_sh_opacity_logscale
  compare_space: teacher
  projector:
    in_dim: 192
    out_dim: 52
  teacher_adapter: null
  student_adapter: null
  allow_dim_mismatch: false
  boundary_mask_threshold: 0.60
  boundary_mask_soft_transition: 0.10
  mask_controller: null

logging:
  tensorboard: logs/lego/feat_t_full/runs/teacher_full_psnr20_quickwin/tensorboard
  csv: logs/lego/feat_t_full/runs/teacher_full_psnr20_quickwin/training_metrics.csv
  render_preview_interval: 5000
  log_interval: 50
  tensorboard_flush_secs: 15

dataset: {frames: 200, size: 800}
background: masked_white

