name: kilogs
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - pytorch-cuda=11.8
  - cuda-toolkit=11.8
  - numpy<2
  - scipy
  - scikit-image
  - opencv
  - imageio
  - pillow
  - matplotlib
  - tqdm
  - tensorboard
  - hydra-core
  - pyyaml
  - click
  - pip
  - pip:
      - lpips
      - pynvml
      - nerfacc
      - pyquaternion
      - tinycudann
      - ninja
